{{- if and .Values.tailscale.enabled .Values.tailscale.authKey.value (not .Values.tailscale.authKey.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpubox.tailscaleAuthSecretName" . }}
  labels:
    {{- include "gpubox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tailscale.authKey.secretKey | quote }}: {{ .Values.tailscale.authKey.value | quote }}
{{- end }}
