FROM docker/buildkit-syft-scanner@sha256:ae4f3b554449e7e25548e7d8ccc029d17357348e30c6e3df01b92bc93654d6a9 AS upstream

FROM scratch
COPY --from=upstream /bin/syft-scanner /bin/syft-scanner
COPY bin/gpubox-sbom-generator /bin/gpubox-sbom-generator
ENTRYPOINT ["/bin/gpubox-sbom-generator"]
