FROM docker/buildkit-syft-scanner@sha256:79e7b013cbec16bbb436f312819a49a4a57752b2270c1a9332ae1a10fcc82a68 AS upstream

FROM scratch
COPY --from=upstream /bin/syft-scanner /bin/syft-scanner
COPY bin/gpubox-sbom-generator /bin/gpubox-sbom-generator
ENTRYPOINT ["/bin/gpubox-sbom-generator"]
